### ISSUE TITLE
Mongoose Cast Error: Cast to string failed on dev server

### ISSUE THREAD

**Issue by tylandavis** [payloadcms/nextjs-custom-server#10]
# Issue
Following installation steps and then creating a page in the default Pages collection, an error occurs when visiting that page at localhost:3000/test-page:

`CastError: Cast to string failed for value "[ 'test-page' ]" (type Array) at path "slug" for model "pages"`

A similar error appears in the console when in the admin panel, this one for the 'favicon.ico' file:

`CastError: Cast to string failed for value "[ 'favicon.ico' ]" (type Array) at path "slug" for model "pages"`

## Possible Solution
I have not run into this before when using Payload from scratch with Javascript, so I wonder if this may be caused by a clash between the Typescript and Mongoose 'type' declarations. Some quick research led me to [the 'typeKey' option for Mongoose schemas](https://mongoosejs.com/docs/guide.html#typeKey). I don't know enough about Mongoose schemas or how Payload handles them to explore a fix for this.

## Steps to reproduce
1. Clone repo.
2. Set up `.env` variables.
3. yarn
4. yarn dev
5. Create user
6. Open admin panel (this is where the favicon error first appears).
7. Create new page in Pages collection with slug 'test-page'.
8. Go to localhost:3000/test-page
9. Cast error

## Details
- Payload versions 0.13.2 and 0.15.2 tested with similar errors.
- Serverless instance of MongoDB Atlas.
- Screenshot of error below
<img width="981" alt="Screen Shot 2022-05-09 at 9 10 29 PM" src="https://user-images.githubusercontent.com/89618855/167528899-214922c5-68e0-4df2-9999-56f5119d0f67.png">

**Comment by jmikrut** [comment]
Hey @tylandavis — the issue here arises from the fact that the `slug` is actually an array of strings, because the NextJS page template filename is `[...slug]`. So you could have any number of slugs. For example, in the case of `/company/team/leadership`, the `slug` const would equal `['company', 'team', 'leadership']`.

Then, we're trying to create a Payload query with that slug. But, the `slug` is actually saved in the database as a `string`, so Mongoose complains when we try to search on a string in the database with a value equal to an array of strings. 

This is a bug with this NextJS boilerplate and should be easily solved. We'll get it sorted!

**Comment by JessRynkar** [comment]
Hi @tylandavis - this issue has been resolved, you can go ahead and pull from the master branch to get this update. Thank you for submitting this issue and let us know if you need anything else!
